version: '2.4'
services:
  ctftime_bot:
    build: ./app
    container_name: bot
    restart: always
    env_file:
      - .env
    depends_on:
      - ctftime_db

  ctftime_db:
      image: postgres:13.0
      restart: always
      container_name: ctftime_db
      volumes:
        - postgres_data:/var/lib/postgresql/data/
        - ./migrations:/docker-entrypoint-initdb.d
      env_file:
        - .env

volumes:
  postgres_data: